version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
    volumes:
      - ./web/src:/var/www/html/

  db:
    container_name: db
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8889:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8890:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
